package td2;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;


public class App {
    public static void main(String[] args) {
        // exercice 1 Question 1

        Somme<Integer> sommeInt = (x, y) -> x + y;

        Somme<Double> sommeDouble = (x, y) -> x + y;

        Somme<Long> sommeLong = (x, y) -> x + y;
        
        Somme<String> sommeString = (x, y) -> x.concat(y);

        // exercice 1 Question 2
        
        List<String> l2s = new ArrayList<>();
        l2s.add("e1");
        l2s.add("e2");
        
        ToString<List<String>> toStringList = x ->
        {
            final StringBuilder builder = new StringBuilder();
            x.forEach((val) ->
            {
                builder.append(val + ", ");

            });
            return builder.toString();
        };

        System.out.println(toStringList.show(l2s));

        HashMap<String, Integer> hm = new HashMap<>();
        hm.put("k1", 1);
        hm.put("k2", 2);
        ToString<HashMap<String, Integer>> toStringMap = x ->
        {
            final StringBuilder builder = new StringBuilder();
            x.forEach((key, val) ->
            {
                builder.append(String.format("%s : %d, ", key, val));
            });
            return builder.toString();
        };
        
        System.out.println(toStringMap.show(hm));

    }

}
